export interface AndroidFile {
  path: string;
  name: string;
  language: 'kotlin' | 'xml' | 'gradle' | 'properties' | 'bash' | 'yaml' | 'dart' | 'json' | 'markdown';
  category: 'manifest' | 'gradle' | 'kotlin' | 'layout' | 'resource' | 'root' | 'flutter' | 'workflow' | 'asset' | 'doc';
  content: string;
}

export const GRADLEW_SCRIPT = `#!/bin/sh
##############################################################################
#   Gradle start up script for POSIX generated by Gradle.
#   zyChat Android APK Build Wrapper
##############################################################################

app_path=$0
while [ -h "$app_path" ]; do
    ls=$(ls -ld "$app_path")
    link=$(expr "$ls" : '.*-> \\(.*\\)$')
    if expr "$link" : '/.*' > /dev/null; then
        app_path="$link"
    else
        app_path=$(dirname "$app_path")"/$link"
    fi
done

APP_BASE_NAME=\${0##*/}
APP_HOME=$(cd "$(dirname "$app_path")" && pwd -P) || exit

DEFAULT_JVM_OPTS='"-Xmx1024m" "-Xms256m"'

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

# Fallback: if gradle is installed on CI runner, run gradle directly
if [ ! -f "$CLASSPATH" ]; then
    if command -v gradle >/dev/null 2>&1; then
        exec gradle "$@"
    fi
fi

eval set -- "$DEFAULT_JVM_OPTS" "$JAVA_OPTS" "$GRADLE_OPTS" "\\"-Dorg.gradle.appname=$APP_BASE_NAME\\"" -classpath "\\"$CLASSPATH\\"" org.gradle.wrapper.GradleWrapperMain '"$@"'
exec "$JAVACMD" "$@"
`.replace(/\r\n/g, '\n');

export const GRADLEW_BAT = `@rem Gradle startup script for Windows
@rem zyChat Android Base APK Build Wrapper
@if "%DEBUG%" == "" @echo off
set DIRNAME=%~dp0
if "%DIRNAME%" == "" set DIRNAME=.
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

set DEFAULT_JVM_OPTS="-Xmx1024m" "-Xms256m"
set CLASSPATH=%APP_HOME%\\gradle\\wrapper\\gradle-wrapper.jar

java.exe %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*
`.replace(/\r\n/g, '\n');

export const ROOT_BUILD_GRADLE = `buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.21'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`.replace(/\r\n/g, '\n');

export const ROOT_SETTINGS_GRADLE = `pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "zyChat"
include ":app"
`.replace(/\r\n/g, '\n');

export const GRADLE_PROPERTIES = `org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
`.replace(/\r\n/g, '\n');

export const GRADLE_WRAPPER_PROPERTIES = `distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-8.10.2-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
`.replace(/\r\n/g, '\n');

export const APP_BUILD_GRADLE = `plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.zychat.fake'
    compileSdk 34

    defaultConfig {
        applicationId "com.zychat.fake"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
        debug {
            applicationIdSuffix ".debug"
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
    implementation 'androidx.webkit:webkit:1.11.0'
}
`.replace(/\r\n/g, '\n');

export const ANDROID_MANIFEST_XML = `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.zychat.fake">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher"
        android:supportsRtl="true"
        android:theme="@style/Theme.ZyChat"
        android:usesCleartextTraffic="true">
        
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
`.replace(/\r\n/g, '\n');

export const MAIN_ACTIVITY_KT = `package com.zychat.fake

import android.annotation.SuppressLint
import android.os.Bundle
import android.webkit.PermissionRequest
import android.webkit.WebChromeClient
import android.webkit.WebSettings
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {

    private lateinit var webView: WebView

    @SuppressLint("SetJavaScriptEnabled")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        webView = WebView(this)
        setContentView(webView)

        val settings: WebSettings = webView.settings
        settings.javaScriptEnabled = true
        settings.domStorageEnabled = true
        settings.databaseEnabled = true
        settings.mediaPlaybackRequiresUserGesture = false
        settings.allowFileAccess = true
        settings.allowContentAccess = true

        webView.webViewClient = WebViewClient()
        webView.webChromeClient = object : WebChromeClient() {
            override fun onPermissionRequest(request: PermissionRequest?) {
                request?.grant(request.resources)
            }
        }

        // Muat zyChat dari assets lokal atau online
        webView.loadUrl("file:///android_asset/www/index.html")
    }

    override fun onBackPressed() {
        if (this::webView.isInitialized && webView.canGoBack()) {
            webView.goBack()
        } else {
            super.onBackPressed()
        }
    }
}
`.replace(/\r\n/g, '\n');

export const STRINGS_XML = `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">zyChat</string>
    <string name="app_tagline">WhatsApp Fake Experience</string>
</resources>
`.replace(/\r\n/g, '\n');

export const COLORS_XML = `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="whatsapp_green">#00A884</color>
    <color name="whatsapp_teal">#008069</color>
    <color name="whatsapp_dark">#111B21</color>
    <color name="whatsapp_dark_surface">#202C33</color>
    <color name="whatsapp_light_bg">#EFEAE2</color>
    <color name="white">#FFFFFF</color>
    <color name="black">#000000</color>
</resources>
`.replace(/\r\n/g, '\n');

export const STYLES_XML = `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Theme.ZyChat" parent="Theme.AppCompat.DayNight.NoActionBar">
        <item name="colorPrimary">@color/whatsapp_teal</item>
        <item name="colorPrimaryDark">@color/whatsapp_dark</item>
        <item name="colorAccent">@color/whatsapp_green</item>
        <item name="android:windowBackground">@color/whatsapp_dark</item>
    </style>
</resources>
`.replace(/\r\n/g, '\n');

export const GITHUB_WORKFLOW_YML = `name: Build zyChat Android APK

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-apk:
    name: Build zyChat APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Web Dependencies
        run: npm install

      - name: Build Web Application
        run: npm run build

      - name: Prepare Android Assets
        run: |
          mkdir -p app/src/main/assets/www
          cp -r dist/* app/src/main/assets/www/

      - name: Make Gradle Wrapper Executable
        run: chmod +x gradlew || true

      - name: Build Android APK with Gradle
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zyChat-Android-APK
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 14
`.replace(/\r\n/g, '\n');

export const README_GUIDE_MD = `# zyChat - WhatsApp Fake Experience Base APK

zyChat adalah aplikasi simulasi chat WhatsApp fake lengkap dengan voice note, video call, status/story, komunitas, dan fitur prank obrolan yang otentik.

## 🚀 1. Cara Build Menjadi APK lewat GitHub Actions
1. Push repository ini ke GitHub:
   \`\`\`bash
   git add .
   git commit -m "feat: zyChat Base APK"
   git push origin main
   \`\`\`
2. Buka tab **Actions** di repo GitHub Anda.
3. Jalankan atau tunggu workflow **Build zyChat Android APK** selesai (~2 menit).
4. Unduh file **zyChat-Android-APK** dari section **Artifacts** di halaman selesai build.
5. Install \`zyChat-debug.apk\` langsung ke smartphone Android Anda!

## 🌐 2. Cara Deploy ke Netlify
1. Hubungkan repo ke Netlify, atau jalankan perintah:
   \`\`\`bash
   npm run build
   netlify deploy --prod --dir=dist
   \`\`\`
2. File \`netlify.toml\` sudah otomatis terkonfigurasi untuk Single Page App (SPA).

## ⚡ 3. Cara Deploy ke Vercel
1. Hubungkan repo ke Vercel, atau jalankan perintah:
   \`\`\`bash
   npm run build
   vercel --prod
   \`\`\`
2. File \`vercel.json\` sudah otomatis terkonfigurasi untuk rewrite URL.
`.replace(/\r\n/g, '\n');

export const ANDROID_PROJECT_FILES: AndroidFile[] = [
  {
    path: 'gradlew',
    name: 'gradlew (Executable POSIX Script)',
    language: 'bash',
    category: 'root',
    content: GRADLEW_SCRIPT,
  },
  {
    path: 'gradlew.bat',
    name: 'gradlew.bat (Windows Batch)',
    language: 'bash',
    category: 'root',
    content: GRADLEW_BAT,
  },
  {
    path: 'build.gradle',
    name: 'build.gradle (Root)',
    language: 'gradle',
    category: 'root',
    content: ROOT_BUILD_GRADLE,
  },
  {
    path: 'settings.gradle',
    name: 'settings.gradle',
    language: 'gradle',
    category: 'root',
    content: ROOT_SETTINGS_GRADLE,
  },
  {
    path: 'gradle.properties',
    name: 'gradle.properties',
    language: 'properties',
    category: 'root',
    content: GRADLE_PROPERTIES,
  },
  {
    path: 'gradle/wrapper/gradle-wrapper.properties',
    name: 'gradle/wrapper/gradle-wrapper.properties',
    language: 'properties',
    category: 'gradle',
    content: GRADLE_WRAPPER_PROPERTIES,
  },
  {
    path: 'app/build.gradle',
    name: 'app/build.gradle',
    language: 'gradle',
    category: 'gradle',
    content: APP_BUILD_GRADLE,
  },
  {
    path: 'app/src/main/AndroidManifest.xml',
    name: 'app/src/main/AndroidManifest.xml',
    language: 'xml',
    category: 'manifest',
    content: ANDROID_MANIFEST_XML,
  },
  {
    path: 'app/src/main/java/com/zychat/fake/MainActivity.kt',
    name: 'MainActivity.kt',
    language: 'kotlin',
    category: 'kotlin',
    content: MAIN_ACTIVITY_KT,
  },
  {
    path: 'app/src/main/res/values/strings.xml',
    name: 'res/values/strings.xml',
    language: 'xml',
    category: 'resource',
    content: STRINGS_XML,
  },
  {
    path: 'app/src/main/res/values/colors.xml',
    name: 'res/values/colors.xml',
    language: 'xml',
    category: 'resource',
    content: COLORS_XML,
  },
  {
    path: 'app/src/main/res/values/styles.xml',
    name: 'res/values/styles.xml',
    language: 'xml',
    category: 'resource',
    content: STYLES_XML,
  },
  {
    path: '.github/workflows/build-apk.yml',
    name: '.github/workflows/build-apk.yml',
    language: 'yaml',
    category: 'workflow',
    content: GITHUB_WORKFLOW_YML,
  },
  {
    path: 'README.md',
    name: 'README.md (Panduan GitHub, Vercel & Netlify)',
    language: 'markdown',
    category: 'doc',
    content: README_GUIDE_MD,
  },
];
